[profile.default]
# build_info = true
# extra_output = ["storageLayout"]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin=lib/openzeppelin-contracts/contracts",
    "@openzeppelin-upgradeable=lib/openzeppelin-contracts-upgradeable/contracts"
]

[rpc_endpoints]
sepolina = "${SEPOLINA_RPC_URL}"
localhost = "${LOCAL_RPC_URL_ANVIL}"

# [etherscan]
# sepolina = { key = "${ETHERSCAN_API_KEY}"}
# See more config options https://github.com/foundry-rs/foundry/tree/master/config



